[project]
name = "dynamic-systems"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cmake>=4.1.0",
    "ipykernel>=7.1.0",
    "ipympl>=0.9.8",
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "pandas>=2.3.3",
    "pillow>=11.3.0",
    "ruff>=0.13.3",
    "scikit-learn>=1.8.0",
    "scipy>=1.16.2",
]
